# Generated by Django 5.2.5 on 2025-09-23 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='daily_reset_time',
            field=models.TimeField(default=datetime.time(3, 0)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('DAILY', 'Ежедневная'), ('YELLOW', 'Среднесрочная'), ('RED', 'Долгосрочная')], default='DAILY', max_length=10),
        ),
    ]
