# Generated by Django 5.2.5 on 2025-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_daily_reset_time_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
