# Generated by Django 5.2.5 on 2025-09-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_migrate_completed_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='completion_date',
        ),
    ]
