# Generated by Django 5.2.5 on 2025-09-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_goal_completed_remove_goal_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='timezone',
        ),
    ]
