# Generated by Django 5.2.5 on 2025-09-30 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_character_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='xp_reward',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
