# Generated by Django 5.2.5 on 2025-10-04 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_goal_xp_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_description', models.CharField(max_length=255)),
                ('skill_name', models.CharField(max_length=100)),
                ('xp_amount', models.IntegerField()),
                ('action', models.CharField(choices=[('COMPLETED', 'Выполнена'), ('REVERTED', 'Отменена')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal History Entry',
                'verbose_name_plural': 'Goal History Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
