# Generated by Django 5.2.5 on 2025-09-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_goalcompletion_verified_by_alter_skill_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcompletion',
            name='verified_by',
        ),
    ]
