# Generated by Django 5.2.5 on 2025-10-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_goalcompletion_verified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['id']},
        ),
    ]
