# Generated by Django 5.2.5 on 2025-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_goal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalhistory',
            name='action',
            field=models.CharField(choices=[('COMPLETED', 'Выполнена'), ('REVERTED', 'Отменена'), ('PROGRESS_ADDED', 'Добавлен прогресс')], max_length=20),
        ),
    ]
