# Generated by Django 5.2.5 on 2025-10-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_goalhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalhistory',
            name='skill_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
