# Generated by Django 5.2.5 on 2025-10-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_goal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('DAILY', 'Ежедневная'), ('BLUE', 'Краткосрочная'), ('YELLOW', 'Среднесрочная'), ('RED', 'Долгосрочная')], default='DAILY', max_length=10),
        ),
    ]
