# Generated by Django 5.2.5 on 2025-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalhistory',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('DAILY', 'Ежедневная'), ('BLUE', 'Краткосрочная'), ('YELLOW', 'Среднесрочная'), ('RED', 'Долгосрочная')], max_length=10, null=True),
        ),
    ]
